services:
  directus:
    image: directus/directus:11
    restart: always
    volumes:
      - ./extensions:/directus/extensions
    environment:
      SECRET: ${DIRECTUS_SECRET}
      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
      DB_CLIENT: "postgres"
      DB_HOST: ${DATABASE_HOST}
      DB_PORT: ${DATABASE_PORT}
      DB_DATABASE: ${DATABASE_NAME}
      DB_USER: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      REDIS_ENABLED: "true"
      REDIS: ${REDIS_URL}
      CACHE_ENABLED: "true"
      CACHE_TTL: "6 hrs"
      CACHE_AUTO_PURGE: "true"
      STORAGE_LOCATIONS: "s3"
      STORAGE_S3_DRIVER: "s3"
      STORAGE_S3_KEY: ${DIRECTUS_STORAGE_S3_KEY}
      STORAGE_S3_SECRET: ${DIRECTUS_STORAGE_S3_SECRET}
      STORAGE_S3_BUCKET: ${DIRECTUS_STORAGE_S3_BUCKET}
      STORAGE_S3_REGION: ${DIRECTUS_STORAGE_S3_REGION}
      STORAGE_S3_ENDPOINT: ${DIRECTUS_STORAGE_S3_ENDPOINT}
      PUBLIC_URL: ${PUBLIC_URL}
      CORS_ENABLED: "true"
      CORS_ORIGIN: ${PUBLIC_URL}
    expose:
      - "8055"
    networks:
      shared-proxy:
        aliases:
          - directus-app1

networks:
  shared-proxy:
    external: true
